# Generated by Django 5.0.4 on 2026-05-07 20:25

import django.db.models.deletion
import djangoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_cliente_options_cliente_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaocategoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='produtoavaliacao',
            options={},
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=djangoapp.models.produto_imagem_path)),
                ('principal', models.BooleanField(default=False, help_text='Marque como True para exibir no card da listagem.')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no carrossel do detalhe (menor = primeiro).')),
                ('alt', models.CharField(blank=True, help_text='Texto alternativo para acessibilidade (alt da tag <img>).', max_length=120)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='djangoapp.produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'db_table': 'produto_imagens',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
